const coaches = [
	{
		firstName: "John",
		lastName: "Doe",
		description: "Web Developer",
		link: "https://www.example.com/johndoe",
		status: "active",
	},
	{
		firstName: "Jane",
		lastName: "Smith",
		description: "Graphic Designer",
		link: "https://www.example.com/janesmith",
		status: "active",
	},
	{
		firstName: "Michael",
		lastName: "Johnson",
		description: "Software Engineer",
		link: "https://www.example.com/michaeljohnson",
		status: "inactive",
	},
	{
		firstName: "Emily",
		lastName: "Brown",
		description: "Data Scientist",
		link: "https://www.example.com/emilybrown",
		status: "active",
	},
	{
		firstName: "Daniel",
		lastName: "Wilson",
		description: "UX Designer",
		link: "https://www.example.com/danielwilson",
		status: "inactive",
	},
	{
		firstName: "Sarah",
		lastName: "Clark",
		description: "Marketing Manager",
		link: "https://www.example.com/sarahclark",
		status: "active",
	},
	{
		firstName: "James",
		lastName: "Anderson",
		description: "Frontend Developer",
		link: "https://www.example.com/jamesanderson",
		status: "inactive",
	},
	{
		firstName: "Olivia",
		lastName: "Taylor",
		description: "Content Writer",
		link: "https://www.example.com/oliviataylor",
		status: "active",
	},
	{
		firstName: "William",
		lastName: "Thomas",
		description: "Database Administrator",
		link: "https://www.example.com/williamthomas",
		status: "inactive",
	},
	{
		firstName: "Ava",
		lastName: "Harris",
		description: "UI Designer",
		link: "https://www.example.com/avaharris",
		status: "active",
	},
	{
		firstName: "Liam",
		lastName: "Martin",
		description: "Backend Developer",
		link: "https://www.example.com/liammartin",
		status: "active",
	},
	{
		firstName: "Mia",
		lastName: "White",
		description: "Project Manager",
		link: "https://www.example.com/miawhite",
		status: "inactive",
	},
	{
		firstName: "Ethan",
		lastName: "Jones",
		description: "QA Engineer",
		link: "https://www.example.com/ethanjones",
		status: "active",
	},
	{
		firstName: "Sophia",
		lastName: "Lee",
		description: "Digital Marketer",
		link: "https://www.example.com/sophialeeh",
		status: "active",
	},
	{
		firstName: "Noah",
		lastName: "Wilson",
		description: "DevOps Engineer",
		link: "https://www.example.com/noahwilson",
		status: "inactive",
	},
	{
		firstName: "Isabella",
		lastName: "Smith",
		description: "UI/UX Designer",
		link: "https://www.example.com/isabellasmith",
		status: "active",
	},
	{
		firstName: "Aiden",
		lastName: "Brown",
		description: "System Administrator",
		link: "https://www.example.com/aidenbrown",
		status: "inactive",
	},
	{
		firstName: "Oliver",
		lastName: "Garcia",
		description: "Software Developer",
		link: "https://www.example.com/olivergarcia",
		status: "active",
	},
	{
		firstName: "Amelia",
		lastName: "Davis",
		description: "Content Strategist",
		link: "https://www.example.com/ameliadavis",
		status: "active",
	},
	{
		firstName: "Elijah",
		lastName: "Lopez",
		description: "Full Stack Developer",
		link: "https://www.example.com/elijahlopez",
		status: "inactive",
	},
	{
		firstName: "Charlotte",
		lastName: "Perez",
		description: "Product Designer",
		link: "https://www.example.com/charlotteperez",
		status: "active",
	},
	{
		firstName: "Benjamin",
		lastName: "Miller",
		description: "Data Analyst",
		link: "https://www.example.com/benjaminmiller",
		status: "inactive",
	},
	{
		firstName: "Lucas",
		lastName: "Martinez",
		description: "Frontend Developer",
		link: "https://www.example.com/lucasmartinez",
		status: "active",
	},
	{
		firstName: "Aria",
		lastName: "Jackson",
		description: "UX Researcher",
		link: "https://www.example.com/ariajackson",
		status: "active",
	},
	{
		firstName: "Henry",
		lastName: "Wilson",
		description: "Database Administrator",
		link: "https://www.example.com/henrywilson",
		status: "inactive",
	},
	{
		firstName: "Luna",
		lastName: "Gomez",
		description: "Graphic Designer",
		link: "https://www.example.com/lunagomez",
		status: "active",
	},
	{
		firstName: "Alexander",
		lastName: "Davis",
		description: "Backend Developer",
		link: "https://www.example.com/alexanderdavis",
		status: "active",
	},
	{
		firstName: "Mila",
		lastName: "Hernandez",
		description: "Marketing Manager",
		link: "https://www.example.com/milahernandez",
		status: "inactive",
	},
	{
		firstName: "Sebastian",
		lastName: "Brown",
		description: "Web Developer",
		link: "https://www.example.com/sebastianbrown",
		status: "active",
	},
	{
		firstName: "Leah",
		lastName: "Parker",
		description: "Content Writer",
		link: "https://www.example.com/leahparker",
		status: "active",
	},
	{
		firstName: "Carter",
		lastName: "Williams",
		description: "QA Engineer",
		link: "https://www.example.com/carterwilliams",
		status: "inactive",
	},
	{
		firstName: "Evelyn",
		lastName: "Gonzalez",
		description: "Product Manager",
		link: "https://www.example.com/evelyngonzalez",
		status: "active",
	},
	{
		firstName: "Jackson",
		lastName: "Anderson",
		description: "Software Engineer",
		link: "https://www.example.com/jacksonanderson",
		status: "inactive",
	},
	{
		firstName: "Grace",
		lastName: "Hall",
		description: "Digital Marketer",
		link: "https://www.example.com/gracehall",
		status: "active",
	},
	{
		firstName: "Aiden",
		lastName: "Robinson",
		description: "UI/UX Designer",
		link: "https://www.example.com/aidenrobinson",
		status: "active",
	},
	{
		firstName: "Lucas",
		lastName: "Rivera",
		description: "DevOps Engineer",
		link: "https://www.example.com/lucasrivera",
		status: "inactive",
	},
	{
		firstName: "Aria",
		lastName: "Turner",
		description: "Content Strategist",
		link: "https://www.example.com/ariaturner",
		status: "active",
	},
];

const getCoaches = async () => {
	try {
		return { data: coaches };
	} catch (err) {
		throw new Error(err.message);
	}
};

export default getCoaches;
